version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: authz-postgres
    restart: always
    environment:
      POSTGRES_DB: authz_db
      POSTGRES_USER: authz_user
      POSTGRES_PASSWORD: authz_pass
    ports:
      - "5432:5432"
    volumes:
      - authz_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: authz-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # AMQP bağlantısı üçün
      - "15672:15672"   # RabbitMQ UI (http://localhost:15672)

volumes:
  authz_pgdata:
