version: '3.9'

services:
  ms-authz:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: postgres
        DB_NAME: authz
        DB_USERNAME: postgres
        DB_PASSWORD: secret
        RABBITMQ_USER: guest
        RABBITMQ_PASSWORD: guest
        RABBITMQ_HOST: rabbitmq
        PORT: 8080
    container_name: ms-authz
    ports:
      - "8080:8080"
    volumes:
      - ./keys:/app/keys:ro
      - ./docs:/app/docs:ro
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  postgres:
    image: postgres:15
    container_name: authz-db
    restart: always
    environment:
      POSTGRES_DB: authz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - authz_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: authz-rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  authz_postgres_data:
